# Generated by Django 4.2.1 on 2023-05-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testCase', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
    ]
