# Generated by Django 4.2.1 on 2023-05-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelbase', '0004_testcaseinstance_testcases_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseinstance',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testcaseinstance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
