# Generated by Django 4.2.1 on 2023-05-31 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excelbase', '0006_alter_testcases_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='excelbase.testcaseinstance'),
        ),
    ]
